package com.uniquindio.sebas.guia5.doamin;

public enum UserStatus {

    /**
     * DENTRO DE LA LOGICA Y BUENAS PRACTICAS ES IMPORTANTE QUE LOS DATOS NO SE PIERDAN,
     * POR ENDE CUANDO UN OBJETO SE ELIMINE , SE CREE, O ESTE USANDOSE
     * INDICAR EL TIPO DE ESTADO EN EL QUE SE ENCUENTRA, ASI NOS EVITAMOS
     * PERDIDA DE INFORMACION IMPORTANTE
     */
    REGISTERED,DELETED,ACTIVE
}
